// ชุดไอคอนของทั้งระบบ (Lucide, ISC License) — ใช้ร่วมกันทั้งแอป React และจอครัว
// ใช้ไอคอน SVG แทนอีโมจิ เพื่อให้หน้าตาเหมือนกันทุกเครื่อง/ทุกระบบปฏิบัติการ
import {
  ArrowLeft,
  Ban,
  Banknote,
  Bell,
  BellRing,
  ChartColumn,
  ChefHat,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleUserRound,
  ClipboardList,
  Clock,
  CookingPot,
  CupSoda,
  Download,
  ExternalLink,
  Flame,
  Hand,
  House,
  ImageOff,
  Info,
  LayoutGrid,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Menu,
  Minus,
  Music2,
  Pencil,
  Phone,
  Plus,
  Printer,
  QrCode,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Search,
  ShoppingBag,
  Smartphone,
  Sparkles,
  StickyNote,
  Store,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  UtensilsCrossed,
  Volume2,
  VolumeX,
  WifiOff,
  X,
} from 'lucide'

export const ICONS = {
  back: ArrowLeft,
  ban: Ban,
  cash: Banknote,
  bell: Bell,
  bellRing: BellRing,
  chart: ChartColumn,
  chef: ChefHat,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  success: CircleCheck,
  user: CircleUserRound,
  orders: ClipboardList,
  clock: Clock,
  cooking: CookingPot,
  drink: CupSoda,
  download: Download,
  external: ExternalLink,
  flame: Flame,
  hand: Hand,
  home: House,
  noImage: ImageOff,
  info: Info,
  grid: LayoutGrid,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  map: MapPin,
  fullscreen: Maximize,
  menu: Menu,
  minus: Minus,
  music: Music2,
  edit: Pencil,
  phone: Phone,
  plus: Plus,
  print: Printer,
  qr: QrCode,
  receipt: ReceiptText,
  refresh: RefreshCw,
  scan: ScanLine,
  search: Search,
  bag: ShoppingBag,
  transfer: Smartphone,
  sparkles: Sparkles,
  note: StickyNote,
  store: Store,
  timer: Timer,
  trash: Trash2,
  warning: TriangleAlert,
  undo: Undo2,
  food: UtensilsCrossed,
  soundOn: Volume2,
  soundOff: VolumeX,
  offline: WifiOff,
  close: X,
}

// สำหรับหน้า HTML/JS ล้วน (จอครัว): คืนค่าเป็น <svg> element
export function iconElement(name, { size = 20, strokeWidth = 2, className = '' } = {}) {
  const NS = 'http://www.w3.org/2000/svg'
  const svg = document.createElementNS(NS, 'svg')
  const attrs = {
    width: size,
    height: size,
    viewBox: '0 0 24 24',
    fill: 'none',
    stroke: 'currentColor',
    'stroke-width': strokeWidth,
    'stroke-linecap': 'round',
    'stroke-linejoin': 'round',
    'aria-hidden': 'true',
    class: `icon ${className}`.trim(),
  }
  for (const [k, v] of Object.entries(attrs)) svg.setAttribute(k, v)
  for (const [tag, a] of ICONS[name] || []) {
    const child = document.createElementNS(NS, tag)
    for (const [k, v] of Object.entries(a)) child.setAttribute(k, v)
    svg.append(child)
  }
  return svg
}
