// ชุดไอคอนของทั้งระบบ (Lucide, ISC License) — ใช้ผ่าน <Icon name="..." />
// ใช้ไอคอน SVG แทนอีโมจิ เพื่อให้หน้าตาเหมือนกันทุกเครื่อง/ทุกระบบปฏิบัติการ
import {
  ArrowLeft,
  Ban,
  Banknote,
  Bell,
  BellRing,
  ChartColumn,
  ChefHat,
  Check,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  CircleUserRound,
  ClipboardList,
  Clock,
  CookingPot,
  CupSoda,
  Download,
  ExternalLink,
  Flame,
  Hand,
  House,
  ImageOff,
  ImagePlus,
  Info,
  LayoutGrid,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Maximize,
  Menu,
  Minus,
  Music2,
  Pencil,
  Phone,
  Plus,
  Printer,
  QrCode,
  ReceiptText,
  RefreshCw,
  ScanLine,
  Search,
  ShoppingBag,
  Smartphone,
  Sparkles,
  StickyNote,
  Store,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  UtensilsCrossed,
  Volume2,
  VolumeX,
  WifiOff,
  X,
} from 'lucide'

export const ICONS = {
  back: ArrowLeft,
  ban: Ban,
  cash: Banknote,
  bell: Bell,
  bellRing: BellRing,
  chart: ChartColumn,
  chef: ChefHat,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  success: CircleCheck,
  user: CircleUserRound,
  orders: ClipboardList,
  clock: Clock,
  cooking: CookingPot,
  drink: CupSoda,
  download: Download,
  external: ExternalLink,
  flame: Flame,
  hand: Hand,
  home: House,
  noImage: ImageOff,
  imageAdd: ImagePlus,
  info: Info,
  grid: LayoutGrid,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  map: MapPin,
  fullscreen: Maximize,
  menu: Menu,
  minus: Minus,
  music: Music2,
  edit: Pencil,
  phone: Phone,
  plus: Plus,
  print: Printer,
  qr: QrCode,
  receipt: ReceiptText,
  refresh: RefreshCw,
  scan: ScanLine,
  search: Search,
  bag: ShoppingBag,
  transfer: Smartphone,
  sparkles: Sparkles,
  note: StickyNote,
  store: Store,
  timer: Timer,
  trash: Trash2,
  warning: TriangleAlert,
  undo: Undo2,
  food: UtensilsCrossed,
  soundOn: Volume2,
  soundOff: VolumeX,
  offline: WifiOff,
  close: X,
}
